In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

2024-10-23 01:28:07.710667: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 01:28:07.769093: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-23 01:28:07.769127: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-23 01:28:07.771142: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-23 01:28:07.785171: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 01:28:07.785925: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [3]:
df = pd.read_parquet('/cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean_test.parquet')

df[df['modified_sequence'].str.contains('C')]

raw_file  scan_number  \
6           02080d_GA1-TUM_isoform_97_01_01-3xHCD-1h-R1        32268   
8       02245b_BE11-TMT_TUM_isoform_59_01_01-TMT1-1h-R2        40795   
38    03919_BB8-TMT_TUM_second_addon_20_01_01-TMT1-1...        27392   
60    02244b_GG8-TMT_Thermo_SRM_Pool_63_01_01-TMT2-1...        16798   
62          02468b_BC9-TUM_mod_ubi_33_01_01-3xHCD-1h-R1        34677   
...                                                 ...          ...   
1950     03296a_BA6-TUM_mod_pyroGlu_6_01_01-3xHCD-1h-R1        39476   
1954   02079a_BH3-TUM_isoform_87_01_01-2xIT_2xHCD-1h-R3        24879   
1965       01650b_BA6-TUM_first_pool_83_01_01-DDA-1h-R2        51605   
1972  02208a_GE1-TUM_second_addon_49_01_01-2xIT_2xHC...        35019   
1995  02208a_GB12-TUM_second_addon_24_01_01-3xHCD-1h-R1        17173   

      method_nbr precursor_charge_onehot  collision_energy_aligned_normed  \
6              2      [0, 1, 0, 0, 0, 0]                         0.383757   
8              2      [0, 1, 0, 0, 0, 0]                         0.389702   
38             2      [0, 1, 0, 0, 0, 0]                         0.329925   
60             2      [0, 1, 0, 0, 0, 0]                         0.428685   
62             2      [0, 0, 1, 0, 0, 0]                         0.375024   
...          ...                     ...                              ...   
1950           2      [0, 1, 0, 0, 0, 0]                         0.290846   
1954           1      [0, 0, 1, 0, 0, 0]                         0.350000   
1965           2      [0, 1, 0, 0, 0, 0]                         0.319256   
1972           2      [0, 0, 1, 0, 0, 0]                         0.246096   
1995           2      [0, 1, 0, 0, 0, 0]                         0.368186   

                                        intensities_raw               package  \
6     [0.09, 0.0, -1.0, 0.0, 0.0, -1.0, 0.09, 0.0, -...     TUM_isoform_97_01   
8     [0.57, 0.0, -1.0, 0.94, 0.0, -1.0, 1.0, 0.0, -...    TMT_TUM_isoform_59   
38    [0.78, 0.0, -1.0, 0.41, 0.0, -1.0, 1.0, 0.0, -...  TMT_TUM_second_addon   
60    [1.0, 0.0, -1.0, 0.8, 0.0, -1.0, 0.16, 0.0, -1...   TMT_Thermo_SRM_Pool   
62    [0.22, 0.0, 0.0, 0.0, 0.0, 0.0, 0.23, 0.0, 0.0...        TUM_mod_ubi_33   
...                                                 ...                   ...   
1950  [0.21, 0.0, -1.0, 0.0, 0.0, -1.0, 0.1, 0.0, -1...     TUM_mod_pyroGlu_6   
1954  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...     TUM_isoform_87_01   
1965  [0.05, 0.0, -1.0, 0.0, 0.0, -1.0, 0.03, 0.0, -...     TUM_first_pool_83   
1972  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   TUM_second_addon_49   
1995  [0.16, 0.0, -1.0, 0.0, 0.0, -1.0, 0.24, 0.0, -...   TUM_second_addon_24   

                                      modified_sequence  sub  
6                     []-FSNSIPQSQTDGVLLC[UNIMOD:4]R-[]  0.0  
8     [UNIMOD:737]-AATWDSEYLVC[UNIMOD:4]K[UNIMOD:737...  0.0  
38    [UNIMOD:737]-M[UNIMOD:35]C[UNIMOD:4]SSLTAEYK[U...  0.0  
60                  [UNIMOD:737]-EVEC[UNIMOD:4]YSVQR-[]  0.0  
62    []-DFIITPGGC[UNIMOD:4]LKC[UNIMOD:4]K[UNIMOD:12...  0.0  
...                                                 ...  ...  
1950            []-Q[UNIMOD:28]DVHLLMTNC[UNIMOD:4]IK-[]  0.0  
1954                    []-DKLC[UNIMOD:4]SPLSEPGDPSK-[]  0.0  
1965                    []-NAC[UNIMOD:4]LLPAYFAVTEIR-[]  0.0  
1972          []-MLETLTLISSLGC[UNIMOD:4]WHGGEDEAAPSK-[]  0.0  
1995                        []-LFDETC[UNIMOD:4]TEHAK-[]  0.0  

[220 rows x 9 columns]

In [12]:
from models.models import TransformerModel 

model = TransformerModel(
    running_units=256,
    d=64,
    h=4,
    ffn_mult=1,
    depth=3,
    pos_type='learned', # learned
    prec_type="embed_input", # embed_input | pretoken | inject_pre | inject_ffn
    learned_pos=True,
    prenorm=False,
    norm_type="layer",
    penultimate_units=None,
    output_units=174,
    max_charge=6,
    sequence_length=30,
    alphabet=False,
    dropout=0,
    precursor_units=None,
    inject_position="all" # all | pre | post    
)


from dlomix.losses import masked_spectral_distance, masked_pearson_correlation_distance

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer='adam', 
            loss=masked_spectral_distance,
            metrics=[masked_pearson_correlation_distance])

model.build(input_shape=(None, 30))

model.summary()
#models

ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental'

In [2]:
# Prosit dataset

import os
os.environ['HF_HOME'] = "/cmnfs/proj/prosit_astral"
os.environ['HF_DATASETS_CACHE'] = "/cmnfs/proj/prosit_astral/datasets"

print("[UNIMOD:1]-K[UNIMOD:1]".count('[UNIMOD:' + '1' + ']'))

import numpy as np
from dlomix.data import FragmentIonIntensityDataset
import pandas as pd

from datasets import disable_caching
disable_caching()

PTMS_ALPHABET = {
    "A": 1,
    "C": 2,
    "D": 3,
    "E": 4,
    "F": 5,
    "G": 6,
    "H": 7,
    "I": 8,
    "K": 9,
    "L": 10,
    "M": 11,
    "N": 12,
    "P": 13,
    "Q": 14,
    "R": 15,
    "S": 16,
    "T": 17,
    "V": 18,
    "W": 19,
    "Y": 20,
    "M[UNIMOD:35]": 21,
    "R[UNIMOD:7]":22,
    "C[UNIMOD:4]": 2,
    "Q[UNIMOD:7]":4,
    "N[UNIMOD:7]":3,
}

rt_data = FragmentIonIntensityDataset(
    data_source="/cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean_train.parquet",
    val_data_source="/cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean_val.parquet",
    test_data_source="/cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean_test.parquet",
    data_format="parquet", 
    val_ratio=0.2, max_seq_len=30, encoding_scheme="naive-mods",
    vocab=PTMS_ALPHABET,
    model_features=["precursor_charge_onehot", "collision_energy_aligned_normed","method_nbr"],
    batch_size=2048
)

2


/nfs/home/students/d.lochert/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm



Avaliable feature extractors are (use the key of the following dict and pass it to features_to_extract in the Dataset Class):
{
   "atom_count": "Atom count of PTM.",
   "delta_mass": "Delta mass of PTM.",
   "mod_gain": "Gain of atoms due to PTM.",
   "mod_loss": "Loss of atoms due to PTM."
}.
When writing your own feature extractor, you can either
    (1) use the FeatureExtractor class or
    (2) write a function that can be mapped to the Hugging Face dataset.
In both cases, you can access the parsed sequence information from the dataset using the following keys, which all provide python lists:
    - _parsed_sequence: The parsed sequence
    - _n_term_mods: The N-terminal modifications
    - _c_term_mods: The C-terminal modifications



/nfs/home/students/d.lochert/projects/astral/dlomix/src/dlomix/data/dataset.py:169: UserWarning: 
                    Multiple data sources provided {'train': '/cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean_train.parquet', 'val': '/cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean_val.parquet', 'test': '/cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean_test.parquet'}, please ensure that the data sources are already split into train, val and test sets
                    since no splitting will happen. If not, please provide only one data source and set the val_ratio to split the data into train and val sets."
                    
  warnings.warn(
Filter (num_proc=2): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 814/814 [00:00<00:00, 4282.56 examples/s]


In [18]:
rt_data["train"]

Dataset({
    features: ['modified_sequence', 'intensities_raw', 'precursor_charge_onehot', 'collision_energy_aligned_normed', 'method_nbr', '_parsed_sequence', '_n_term_mods', '_c_term_mods'],
    num_rows: 2836
})

In [14]:
rt_data.tensor_train_data

<_PrefetchDataset element_spec=({'modified_sequence': TensorSpec(shape=(None, 30), dtype=tf.float32, name=None), 'precursor_charge_onehot': TensorSpec(shape=(None, 6), dtype=tf.int64, name=None), 'collision_energy_aligned_normed': TensorSpec(shape=(None,), dtype=tf.float32, name=None), 'method_nbr': TensorSpec(shape=(None,), dtype=tf.int64, name=None)}, TensorSpec(shape=(None, 174), dtype=tf.float32, name=None))>

In [26]:
from models.models import TransformerModel 


model = TransformerModel(
    running_units=256,
    d=64,
    h=4,
    ffn_mult=1,
    depth=3,
    pos_type='learned', # learned
    prec_type="pretoken", # embed_input | pretoken | inject_pre | inject_ffn
    learned_pos=True,
    prenorm=False,
    norm_type="layer",
    penultimate_units=None,
    output_units=174,
    max_charge=6,
    sequence_length=30,
    alphabet=False,
    dropout=0,
    precursor_units=None,
    inject_position="all" # all | pre | post    
)


from dlomix.losses import masked_spectral_distance, masked_pearson_correlation_distance

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer='adam', 
            loss=masked_spectral_distance,
            metrics=[masked_pearson_correlation_distance])


optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from callbacks import CyclicLR, LearningRateLogging

cyclicLR = CyclicLR(base_lr=0.000001, max_lr=0.0002, step_size=2, mode='triangular',
                 gamma=0.95)

early_stopping = EarlyStopping(
    monitor="val_loss",
    min_delta=0.001,
    patience=20,
    restore_best_weights=True)

learningRate = LearningRateLogging()


model.fit(
    rt_data.tensor_train_data,
    validation_data=rt_data.tensor_val_data,
    epochs=4,
#    callbacks=[
#        WandbCallback(save_model=False),
#        cyclicLR,
#        early_stopping,
        #save_best,
#        learningRate
#    ]
)

model.summary()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Epoch 1/4
2/2 [==============================] - 16s 4s/step - loss: 0.7404 - masked_pearson_correlation_distance: 0.6821 - val_loss: 0.7023 - val_masked_pearson_correlation_distance: 0.6291
Epoch 2/4
2/2 [==============================] - 8s 3s/step - loss: 0.7113 - masked_pearson_correlation_distance: 0.6377 - val_loss: 0.6785 - val_masked_pearson_correlation_distance: 0.5939
Epoch 3/4
2/2 [==============================] - 8s 2s/step - loss: 0.6879 - masked_pearson_correlation_distance: 0.6046 - val_loss: 0.6720 - val_masked_pearson_correlation_distance: 0.5884
Epoch 4/4
2/2 [==============================] - 8s 3s/step - loss: 0.6688 - masked_pearson_correlation_distance: 0.5802 - val_loss: 0.6615 - val_masked_pearson_correlation_distance: 0.5764
Model: "transformer_model_15"
_________________________________________________________________
 Layer (type)                Output Shape              

In [ ]:
intdata[

In [22]:
ALPHABET_UNMOD = {
    "A": 1,
    "C": 2,
    "D": 3,
    "E": 4,
    "F": 5,
    "G": 6,
    "H": 7,
    "I": 8,
    "K": 9,
    "L": 10,
    "M": 11,
    "N": 12,
    "P": 13,
    "Q": 14,
    "R": 15,
    "S": 16,
    "T": 17,
    "V": 18,
    "W": 19,
    "Y": 20,
    "M[UNIMOD:35]": 21,
    "R[UNIMOD:7]":22,
    "C[UNIMOD:4]": 2,
    "Q[UNIMOD:7]":4,
    "N[UNIMOD:7]":3,
}

from tensorflow.keras.layers.experimental import preprocessing
string_lookup = preprocessing.StringLookup(vocabulary=list(ALPHABET_UNMOD.keys()))


input_embedding = tf.one_hot(string_lookup(["A", "S", "V"]), len(ALPHABET_UNMOD))

input_embedding

for i in rt_data.tensor_train_data:
    print(i)

train_data[0][0]

({'modified_sequence': <tf.Tensor: shape=(2048, 30), dtype=float32, numpy=
array([[nan,  3., 16., ...,  0.,  0.,  0.],
       [nan, 15.,  3., ...,  0.,  0.,  0.],
       [nan,  3., 17., ...,  0.,  0.,  0.],
       ...,
       [nan, 22., 16., ...,  0.,  0.,  0.],
       [nan, 18., 10., ...,  0.,  0.,  0.],
       [nan,  8., 17., ...,  0.,  0.,  0.]], dtype=float32)>, 'precursor_charge_onehot': <tf.Tensor: shape=(2048, 6), dtype=int64, numpy=
array([[0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       ...,
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])>, 'collision_energy_aligned_normed': <tf.Tensor: shape=(2048,), dtype=float32, numpy=
array([0.35      , 0.2860499 , 0.35      , ..., 0.35      , 0.28745976,
       0.28614625], dtype=float32)>, 'method_nbr': <tf.Tensor: shape=(2048,), dtype=int64, numpy=array([2, 1, 2, ..., 2, 1, 1])>}, <tf.Tensor: shape=(2048, 174), dtype=float32, numpy=
array([[ 0.        ,  0.        , -1. 

NameError: name 'train_data' is not defined

In [1]:
from copy import deepcopy
import numpy as np
import tensorflow as tf
K = tf.keras
L = K.layers
A = K.activations
I = K.initializers

2024-05-21 13:04:50.900545: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-21 13:04:50.900601: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-21 13:04:50.900640: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered



class AdaptiveNorm(L.Layer):

    def __init__(self):
        super(AdaptiveNorm, self).__init__()
        self.norm = L.LayerNormalization()
        self.norm.trainable = False

    



layer = AdaptiveNorm()
x = tf.random.normal((10,30,512))


layer(x)



In [3]:
layer.trainable_variables


[]

In [70]:
class AdaptiveNorm(L.Layer):

    def __init__(self):
        super(AdaptiveNorm, self).__init__()
        self.norm = L.LayerNormalization()
        self.norm.trainable = False
        
        
    def build(self, x):
        self.scalebias = L.Dense(2*x[-1], 
                                 use_bias=False, 
                                 kernel_initializer=I.RandomNormal(0, 0.1 * x[-1]**-0.5)) 
    
    def call(self, x, metadata):
         
        scalebias = self.scalebias(metadata)  # (bs, 2*ru)
        scale, bias = tf.split(scalebias, 2, -1) # 2 x (bs, ru)
        
        print(scale.numpy().mean())
        print(scale.numpy().std())
        
        scale = scale[:,None]  # (bs, 1, ru)
        bias = bias[:,None]    # (bs, 1, ru)
        
        out = self.norm(x)
        out = (1 + scale) * out - bias 
        
        return out
        
        
class BaseNorm(L.Layer):

    def __init__(self, norm):
        super(BaseNorm, self).__init__()
        self.norm = norm

    def __call__(self, x, metadata=None):
        if isinstance(self.norm, AdaptiveNorm):
            return self.norm(x, metadata)
        else:
            return self.norm(x)


    
layer = AdaptiveNorm()
x = tf.random.normal((10,30,256))




metadata = tf.random.normal((10,256))

layer(x, metadata)

layer.trainable_variables

base_layer = BaseNorm(layer)

out = base_layer(x, metadata)






-0.0013750743
0.10305293
-0.0013750743
0.10305293


In [5]:
x = tf.random.normal((10,512))

In [36]:
out.numpy().mean()

0.0047188704

In [7]:
tf.split(x, 2, -1)[0].shape

TensorShape([10, 256])

In [23]:
val_data_source =   "/cmnfs/proj/prosit_astral/datasets/full_dlomix_format_val_fixed.parquet"

pd.read_parquet(val_data_source).loc[pd.read_parquet(val_data_source)["machine"] == "timsTOF"]

# pd.read_parquet(val_data_source).iloc[[12674492, 12674493, 14258797]]

Empty DataFrame
Columns: [prosit_sequence, charge, collision_energy, method_nr, machine, intensities_raw, charge_oh, method_nr_oh, machine_oh, modified_sequence]
Index: []

In [11]:
train_data_source = "/cmnfs/proj/prosit_astral/datasets/full_dlomix_format_train_fixed.parquet"
val_data_source =   "/cmnfs/proj/prosit_astral/datasets/full_dlomix_format_val_fixed.parquet"
test_data_source =  "/cmnfs/proj/prosit_astral/datasets/full_dlomix_format_test_fixed.parquet"

print(
    len(pd.read_parquet(train_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(val_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(test_data_source)["modified_sequence"].unique())
)
#print(len(pd.read_parquet(train_data_source)) + len(pd.read_parquet(val_data_source)) + len(pd.read_parquet(test_data_source)))

2245482


In [12]:
# astral
train_data_source = "/cmnfs/proj/prosit_astral/datasets/astral_dlomix_format_train_fixed.parquet"
val_data_source =   "/cmnfs/proj/prosit_astral/datasets/astral_dlomix_format_val_fixed.parquet"
test_data_source =  "/cmnfs/proj/prosit_astral/datasets/astral_dlomix_format_test_fixed.parquet"

print(
    len(pd.read_parquet(train_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(val_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(test_data_source)["modified_sequence"].unique())
)

#print(len(pd.read_parquet(train_data_source)) + len(pd.read_parquet(val_data_source)) + len(pd.read_parquet(test_data_source)))

83135


In [13]:
# timsTOF
train_data_source = "/cmnfs/proj/prosit_astral/datasets/timsTOF_dlomix_format_train.parquet"
val_data_source =   "/cmnfs/proj/prosit_astral/datasets/timsTOF_dlomix_format_val.parquet"
test_data_source =  "/cmnfs/proj/prosit_astral/datasets/timsTOF_dlomix_format_test.parquet"

print(
    len(pd.read_parquet(train_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(val_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(test_data_source)["modified_sequence"].unique())
)

print(len(pd.read_parquet(train_data_source)) + len(pd.read_parquet(val_data_source)) + len(pd.read_parquet(test_data_source)))

188210
231386


In [14]:
# proteomeTools
train_data_source = "/cmnfs/proj/prosit_astral/datasets/proteome_tools_dlomix_format_train.parquet"
val_data_source =   "/cmnfs/proj/prosit_astral/datasets/proteome_tools_dlomix_format_val.parquet"
test_data_source =  "/cmnfs/proj/prosit_astral/datasets/proteome_tools_dlomix_format_test.parquet"

print(
    len(pd.read_parquet(train_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(val_data_source)["modified_sequence"].unique()) +
    len(pd.read_parquet(test_data_source)["modified_sequence"].unique())
)

#print(len(pd.read_parquet(train_data_source)) + len(pd.read_parquet(val_data_source)) + len(pd.read_parquet(test_data_source)))

2115856


In [20]:
# balanced
train_data_source = "/nfs/home/students/d.lochert/projects/astral/dlomix-astral/balanced_dlomix_format_train_fixed.parquet"
val_data_source =   "/nfs/home/students/d.lochert/projects/astral/dlomix-astral/balanced_dlomix_format_val_fixed.parquet"
test_data_source =  "/nfs/home/students/d.lochert/projects/astral/dlomix-astral/balanced_dlomix_format_test_fixed.parquet"

# print(
#     len(pd.read_parquet(train_data_source)["modified_sequence"].unique()) +
#     len(pd.read_parquet(val_data_source)["modified_sequence"].unique()) +
#     len(pd.read_parquet(test_data_source)["modified_sequence"].unique())
# )

# print(len(pd.read_parquet(train_data_source)) + len(pd.read_parquet(val_data_source)) + len(pd.read_parquet(test_data_source)))

# comnbine 
pd.concat([pd.read_parquet(train_data_source), pd.read_parquet(val_data_source), pd.read_parquet(test_data_source)]).groupby("machine")["modified_sequence"].nunique()

machine
Astral                    27677
Orbitrap_Fusion_Lumos    160804
TOF                      161550
Name: modified_sequence, dtype: int64

In [2]:
import pandas as pd

val_data_source =   "/nfs/home/students/d.lochert/projects/astral/dlomix-astral/balanced_dlomix_format_val_fixed.parquet"

tmp = pd.read_parquet(val_data_source).loc[[504001, 504002, 504000, 504004]]


tmp

prosit_sequence  charge  collision_energy method_nr  \
504001       SIIPYLLEA       1          0.316665       HCD   
504002     GFPVVLQQISK       2          0.350000       CID   
504000    EYELLSDELNQK       2          0.300000       HCD   
504004      PLEmLEIALR       2          0.290000       HCD   

                      machine  \
504001  Orbitrap_Fusion_Lumos   
504002  Orbitrap_Fusion_Lumos   
504000                 Astral   
504004                    TOF   

                                          intensities_raw           charge_oh  \
504001  [0.0, -1.0, -1.0, 0.0, -1.0, -1.0, 0.204301074...  [1, 0, 0, 0, 0, 0]   
504002  [0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.02999999932...  [0, 1, 0, 0, 0, 0]   
504000  [0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1....  [0, 1, 0, 0, 0, 0]   
504004  [0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.00485239915...  [0, 1, 0, 0, 0, 0]   

       method_nr_oh machine_oh modified_sequence  
504001       [0, 1]  [0, 0, 1]         SIIPYLLEA  
504002       [1, 0]  [0, 0, 1]       GFPVVLQQISK  
504000       [0, 1]  [1, 0, 0]      EYELLSDELNQK  
504004       [0, 1]  [0, 1, 0]        PLEmLEIALR

In [6]:
tmp2 = tmp.rename({'prosit_sequence': 'peptide sequence', 'charge': 'precursor charge', 'collision_energy': 'collision energy','method_nr': 'fragmentation method', 'machine': 'mass spectrometer', 'intensities_raw':'intensities'}, axis=1)

tmp2

peptide sequence  precursor charge  collision energy  \
504001        SIIPYLLEA                 1          0.316665   
504002      GFPVVLQQISK                 2          0.350000   
504000     EYELLSDELNQK                 2          0.300000   
504004       PLEmLEIALR                 2          0.290000   

       fragmentation method      mass spectrometer  \
504001                  HCD  Orbitrap_Fusion_Lumos   
504002                  CID  Orbitrap_Fusion_Lumos   
504000                  HCD                 Astral   
504004                  HCD                    TOF   

                                              intensities           charge_oh  \
504001  [0.0, -1.0, -1.0, 0.0, -1.0, -1.0, 0.204301074...  [1, 0, 0, 0, 0, 0]   
504002  [0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.02999999932...  [0, 1, 0, 0, 0, 0]   
504000  [0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1....  [0, 1, 0, 0, 0, 0]   
504004  [0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.00485239915...  [0, 1, 0, 0, 0, 0]   

       method_nr_oh machine_oh modified_sequence  
504001       [0, 1]  [0, 0, 1]         SIIPYLLEA  
504002       [1, 0]  [0, 0, 1]       GFPVVLQQISK  
504000       [0, 1]  [1, 0, 0]      EYELLSDELNQK  
504004       [0, 1]  [0, 1, 0]        PLEmLEIALR

In [10]:
len(pd.read_parquet(test_data_source)["modified_sequence"].unique())

52125